version: '3.8'

services:
  ailiabcu121:
    image: ailiabcu121
    container_name: ailiabcu121
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - "./models:/models"
      - "./custom_nodes:/custom_nodes"
      - "./input:/input"
      - "./output:/output"
      - "./user:/user"
      - "comfy_venvcu121:/comfy_env"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: ["/comfy_env/bin/python", "main.py", "--listen", "0.0.0.0", "--port", "8188"]

volumes:
  comfy_venvcu121:
    driver: local
